import type {
  LightboxImage,
  PlaceMedia,
  VisualImage,
  VisualSection,
  VisualVideo,
} from "@/components/real/place/types";
import { publicMediaUrl } from "@/components/media/publicMedia";

const imageBase = "/images/real/belize";

function localImage(fileName: string) {
  return `${imageBase}/${fileName}`;
}

const watermarkCropPositions = new Map<string, string>([
  ["blz-001", "50% 0%"],
  ["blz-005", "50% 0%"],
  ["blz-007", "50% 0%"],
  ["blz-009", "50% 0%"],
  ["blz-011", "50% 0%"],
  ["blz-012", "50% 0%"],
  ["blz-013", "50% 0%"],
  ["blz-014", "50% 0%"],
  ["blz-015", "50% 0%"],
  ["blz-016", "50% 25%"],
  ["blz-018", "50% 0%"],
  ["blz-019", "50% 25%"],
  ["blz-020", "50% 25%"],
  ["blz-021", "50% 0%"],
  ["blz-022", "50% 0%"],
  ["blz-023", "50% 0%"],
  ["blz-024", "50% 0%"],
  ["blz-025", "50% 0%"],
  ["blz-026", "50% 0%"],
  ["blz-027", "50% 0%"],
  ["blz-028", "50% 0%"],
  ["blz-029", "50% 0%"],
  ["blz-030", "50% 0%"],
  ["blz-031", "50% 0%"],
  ["blz-032", "50% 0%"],
  ["blz-033", "50% 0%"],
  ["blz-034", "50% 0%"],
  ["blz-035", "50% 0%"],
  ["blz-036", "50% 0%"],
  ["blz-037", "50% 0%"],
]);

function image(item: Omit<VisualImage, "kind">): VisualImage {
  const cropPosition = item.cropPosition ?? watermarkCropPositions.get(item.id);

  return {
    kind: "image",
    ...item,
    ...(cropPosition ? { cropPosition } : {}),
    note: undefined,
  };
}

function video(item: Omit<VisualVideo, "kind">): VisualVideo {
  const { title, subtitle, ...rest } = item;

  return {
    kind: "video",
    ...rest,
    eyebrow: title,
    title: subtitle ?? title,
    note: undefined,
  };
}

export const heroImage: LightboxImage = {
  title: "Blue Hole",
  subtitle: "Reef and deep water from above.",
  src: localImage("blz-007.jpg"),
  cropPosition: "50% 35%",
  imageZoom: 1.00,
  imageShiftY: "0%",
};

export const visualSections: VisualSection[] = [
  {
    id: "Caribbean Sea",
    number: "01",
    title: "Caribbean Sea",
    description: "into blue water, coral shadows, and slow-moving creatures.",
    imagePreviewLimit: 3,
    videoPreviewLimit: 1,
    preserveImageShapes: true,
    items: [
      image({
        id: "blz-007",
        title: "Great Blue Hole",
        subtitle: "Looking down on the world's largest blue hole.",
        note: "A circle of darkness inside the reef.",
        src: localImage("blz-007.jpg"),
        crop: "center",
        cropPosition: "50% 0%",
        imageZoom: 1.0,
        imageShiftY: "0%",
        shape: "large",
      }),
      image({
  id: "blz-001",
  title: "Underwater",
  subtitle: "Selfie I took when scuba diving.",
  note: "The coral reef lies beneath me.",
  src: localImage("blz-001.jpg"),
  crop: "center",
  cropPosition: "50% 70%",
  imageZoom: 1.0,
  imageShiftY: "0%",
  shape: "small",
}),
 image({
  id: "blz-005",
  title: "Reef Boat",
  subtitle: "A boat crossing pale water.",
  note: "The sea opens in layers of blue.",
  src: localImage("blz-005.jpg"),
  crop: "center",
  cropPosition: "50% 35%",
  imageZoom: 1.08,
  imageShiftY: "0%",
  shape: "small",
}),
image({
        id: "blz-029",
        title: "Seaside Restaurant",
        subtitle: "A quiet rest after diving.",
        src: localImage("blz-029.webp"),
        crop: "top",
        shape: "small",
      }),

      image({
        id: "blz-006",
        title: "Inside Blue Hole",
        subtitle: "40 metres below the Great Blue Hole",
        note: "Light thins as the wall drops away.",
        src: localImage("blz-006.jpg"),
        crop: "center",
        shape: "large",
      }),

      video({
        id: "blz-v008",
        title: "Blue Hole Flight",
        subtitle: "A slow pass over reef and open blue.",
        note: "The only Belize video currently used on this page.",
        src: publicMediaUrl("videos/real/belize/blz-v008.mp4"),
        poster: localImage("blz-v008-poster.jpg"),
        shape: "video-wide",
      }),
    ],
  },
  {
    id: "maya-ruins",
    number: "02",
    title: "Maya Ruins",
    description:
      "stone, jungle, and the remains of a vanished ceremonial world.",
    imagePreviewLimit: 3,
    preserveImageShapes: true,
    items: [
      image({
        id: "blz-009",
        title: "Lamanai Path",
        subtitle: "Stone, grass, and jungle edges.",
        note: "The path holds the ruins in green silence.",
        src: localImage("blz-009.jpg"),
        crop: "center",
        cropPosition: "50% 10%",
  imageZoom: 1.05,
  imageShiftY: "0%",
        shape: "large",
      }),
      image({
        id: "blz-010",
        title: "Maya Temple",
        subtitle: "A selfie beside the Maya temple.",
        note: "Heat and stone press close together.",
        src: localImage("blz-010.jpg"),
        crop: "top",
        cropPosition: "50% 90%",
  imageZoom: 1,
  imageShiftY: "0%",
        shape: "small",
      }),
      image({
        id: "blz-011",
        title: "Temple Front",
        subtitle: "Steps rising from the grass.",
        note: "The structure keeps its weight in the sun.",
        src: localImage("blz-011.jpg"),
        crop: "center",
        cropPosition: "50% 0%",
  imageZoom: 1.0,
  imageShiftY: "0%",
        shape: "small",
      }),
      image({
        id: "blz-012",
        title: "Stone Temple",
        subtitle: "Carved walls inside the trees.",
        note: "The jungle gathers around the stone.",
        src: localImage("blz-012.jpg"),
        crop: "center",
        cropPosition: "50% 0%",
  imageZoom: 1.0,
  imageShiftY: "0%",
        shape: "small",
      }),
      image({
        id: "blz-036",
        title: "Ruins",
        subtitle: "A tree rising through the ruins.",
        src: localImage("blz-036.webp"),
        crop: "top",
        shape: "small",
      }),
      image({
        id: "blz-013",
        title: "Palms and Stone",
        subtitle: "A temple framed by palms.",
        note: "The old wall rises through shade and light.",
        src: localImage("blz-013.jpg"),
        crop: "center",
        cropPosition: "50% 0%",
  imageZoom: 1.18,
  imageShiftY: "0%",
        shape: "large",
      }),
      image({
        id: "blz-038",
        title: "ATM Cave",
        subtitle: "Ritual objects deep inside the cave.",
        src: localImage("blz-038.webp"),
        crop: "center",
        shape: "large",
      }),
      image({
        id: "blz-039",
        title: "ATM Cave",
        subtitle: "Ritual objects deep inside the cave.",
        src: localImage("blz-039.webp"),
        crop: "center",
        shape: "small",
      }),

      image({
        id: "blz-041",
        title: "ATM Cave",
        subtitle: "Ritual objects deep inside the cave.",
        src: localImage("blz-041.webp"),
        crop: "center",
        shape: "small",
      }),
       image({
        id: "blz-040",
        title: "ATM Cave",
        subtitle: "Ritual objects deep inside the cave.",
        src: localImage("blz-040.webp"),
        crop: "center",
        cropPosition: "50% 35%",
        shape: "large",
      }),
    ],
  },
  {
    id: "life-fragments",
    number: "03",
    title: "Life Fragments",
    description:
      "small scenes gathered between sea, streets, animals, and evening light.",
    imagePreviewLimit: 3,
    preserveImageShapes: true,
    items: [
      image({
        id: "blz-014",
        title: "Iguana",
        subtitle: "Stillness on warm wood.",
        note: "A small body pauses in the shade.",
        src: localImage("blz-014.jpg"),
        crop: "center",
        shape: "large",
      }),
      image({
        id: "blz-015",
        title: "Dog",
        subtitle: "An afternoon nap on the sofa.",
        note: "Afternoon settles into the cushion.",
        src: localImage("blz-015.jpg"),
        crop: "center",
        shape: "small",
      }),
      image({
        id: "blz-016",
        title: "Pier Light",
        subtitle: "A lamp over evening water.",
        note: "The pier holds the last colour of the day.",
        src: localImage("blz-016.jpg"),
        crop: "center",
        shape: "small",
      }),
      image({
        id: "blz-028",
        title: "Food",
        subtitle: "A taste of local Belizean food.",
        src: localImage("blz-028.webp"),
        crop: "top",
        shape: "small",
      }),
      image({
        id: "blz-018",
        title: "Hermit Crab",
        subtitle: "A small shell against bark.",
        note: "The smallest movements mark the surface.",
        src: localImage("blz-018.jpg"),
        crop: "center",
        shape: "small",
      }),
      image({
        id: "blz-019",
        title: "Beach Palm",
        subtitle: "A palm over pale water.",
        note: "The coast stays simple in the wind.",
        src: localImage("blz-019.jpg"),
        crop: "center",
        cropPosition: "50% 50%",
        shape: "large",
      }),
      image({
        id: "blz-020",
        title: "Seaside Street",
        subtitle: "Colour, palms, and water ahead.",
        note: "The street opens quietly toward the sea.",
        src: localImage("blz-020.jpg"),
        crop: "center",
        cropPosition: "20% 70%",
        shape: "large",
      }),
      image({
        id: "blz-021",
        title: "Dock Chairs",
        subtitle: "Two chairs facing the water.",
        note: "Rest waits at the end of the dock.",
        src: localImage("blz-021.jpg"),
        crop: "center",
        shape: "small",
      }),
      image({
        id: "blz-022",
        title: "Frangipani",
        subtitle: "Its fragrance lingered in the air.",
        note: "A bright detail beside the heat.",
        src: localImage("blz-022.jpg"),
        crop: "center",
        shape: "small",
      }),
      image({
        id: "blz-023",
        title: "Palapa Dock",
        subtitle: "A shaded place near the water.",
        note: "The roof makes a small shelter from the glare.",
        src: localImage("blz-023.jpg"),
        crop: "center",
        shape: "small",
      }),
      image({
        id: "blz-024",
        title: "Night Drinks",
        subtitle: "A dark table after sunset.",
        note: "The night gathers around glass and light.",
        src: localImage("blz-024.jpg"),
        crop: "center",
        shape: "small",
      }),
      image({
        id: "blz-025",
        title: "Sea Sunset",
        subtitle: "Orange light over the water.",
        note: "The horizon lowers into colour.",
        src: localImage("blz-025.jpg"),
        crop: "center",
        shape: "large",
      }),
      image({
        id: "blz-026",
        title: "Cat",
        subtitle: "A cat in pink light.",
        note: "A small domestic pause between days.",
        src: localImage("blz-026.jpg"),
        crop: "center",
        shape: "large",
      }),
      image({
        id: "blz-027",
        title: "Food",
        subtitle: "A taste of local Belizean food.",
        note: "Morning appears in small pieces.",
        src: localImage("blz-027.jpg"),
        crop: "center",
        shape: "small",
      }),
      image({
        id: "blz-030",
        title: "Cat",
        subtitle: "A quiet, lazy hour.",
        src: localImage("blz-030.webp"),
        crop: "top",
        shape: "small",
      }),
      image({
        id: "blz-031",
        title: "Sunset",
        subtitle: "A golden moment by the sea.",
        src: localImage("blz-031.webp"),
        crop: "top",
        shape: "small",
      }),
      image({
        id: "blz-032",
        title: "Food",
        subtitle: "A taste of local Belizean food.",
        src: localImage("blz-032.webp"),
        crop: "top",
        shape: "small",
      }),
      image({
        id: "blz-033",
        title: "Food",
        subtitle: "A taste of local Belizean food.",
        src: localImage("blz-033.webp"),
        crop: "top",
        shape: "large",
      }),
      image({
        id: "blz-034",
        title: "Food",
        subtitle: "A taste of local Belizean food.",
        src: localImage("blz-034.webp"),
        crop: "top",
        shape: "large",
      }),
      image({
        id: "blz-035",
        title: "Rainforest Insect",
        subtitle: "A small burst of color in the rainforest.",
        src: localImage("blz-035.webp"),
        crop: "top",
        shape: "small",
      }),
      image({
        id: "blz-037",
        title: "Food",
        subtitle: "A taste of local Belizean food.",
        src: localImage("blz-037.webp"),
        crop: "top",
        shape: "small",
      }),
    ],
  },
];

export const lightboxImages: LightboxImage[] = [
  heroImage,
  ...visualSections.flatMap((section) =>
    section.items.filter((item): item is VisualImage => item.kind === "image"),
  ),
];

const media: PlaceMedia = {
  heroImage,
  visualSections,
};

export default media;
